#%RAML 1.0 NamedExample
get-order-response: |
  {
      "orderStatus": "PENDING_FULFILLMENT",
      "orderId": "84936",
      "quantity": 3,
      "total": 12.34,
      "email": "HCaminita@freemusic25machine.com",
      "shippingAddress":
      {
          "city": "Philadelphia",
          "country": "UNITED_STATES",
          "state": "PA",
          "zip": "18241",
          "addr1": "123 Test St"
      },
      "billingAddress":
      {
          "city": "Philadelphia",
          "country": "UNITED_STATES",
          "state": "PA",
          "zip": "18241",
          "addr1": "123 Test St"
      },
      "customerId": "681",
      "customerName": "Duman Windows Sales",
      "status": "Pending Fulfillment"
  }